// Generado desde build_handoff k=album-data-v3 (2026-07-02). NO editar a mano.
// Fuente: album oficial Panini 1049790673 + checklist contrastada por OCR. Validación: 864 jugadores: 86.6% OCR token-exacto, GT fotos 15/16 + fix BATHUSI.
// Estructura: slot 1 = badge foil (sin nombre) · slot 13 = TEAM PHOTO apaisada · slots 2-12,14-20 = 18 jugadores.

export type Paleta = { frame: string; deep: string; head: string };
export type AlbumTeam = {
  pais: string;
  grupo: string;
  pagina: number;
  roster: Record<string, [string, string]>; // "2".."20" sin "13": [nombre, APELLIDO]; nombre "" = mononímico
};
export type VerifExtra = {
  fed?: string;
  mlang?: string;
  quali?: string[];
  partidos?: { a: string; b: string; hl: string; fecha: string }[];
};

export const ORDER: string[] = ["MEX","RSA","KOR","CZE","CAN","BIH","QAT","SUI","BRA","MAR","HAI","SCO","USA","PAR","AUS","TUR","GER","CUW","CIV","ECU","NED","JPN","SWE","TUN","BEL","EGY","IRN","NZL","ESP","CPV","KSA","URU","FRA","SEN","IRQ","NOR","ARG","ALG","AUT","JOR","POR","COD","UZB","COL","ENG","CRO","GHA","PAN"];

export const PALETAS: Record<string, Paleta> = {
  MEX: { "deep": "#425423", "head": "#892112", "frame": "#779640" },
  RSA: { "deep": "#7C4A00", "head": "#3A315E", "frame": "#DE8500" },
  KOR: { "deep": "#3E4655", "head": "#9A291C", "frame": "#6F7D98" },
  CZE: { "deep": "#3D454C", "head": "#B92E22", "frame": "#6D7C89" },
  CAN: { "deep": "#734924", "head": "#B53C29", "frame": "#CE8341" },
  BIH: { "deep": "#404260", "head": "#D7A402", "frame": "#7377AC" },
  QAT: { "deep": "#61413B", "head": "#844A54", "frame": "#AE756A" },
  SUI: { "deep": "#754724", "head": "#6F2D25", "frame": "#D28042" },
  BRA: { "deep": "#3A5035", "head": "#CB8804", "frame": "#698F5F" },
  MAR: { "deep": "#73422C", "head": "#2B5C38", "frame": "#CE7650" },
  HAI: { "deep": "#3D3E59", "head": "#A82C2D", "frame": "#6E6F9F" },
  SCO: { "deep": "#3D5056", "head": "#3A396D", "frame": "#6D909B" },
  USA: { "deep": "#5E574E", "head": "#485F92", "frame": "#A89C8D" },
  PAR: { "deep": "#723609", "head": "#303368", "frame": "#CC6211" },
  AUS: { "deep": "#837755", "head": "#E14831", "frame": "#EBD598" },
  TUR: { "deep": "#7F481E", "head": "#B73B26", "frame": "#E38237" },
  GER: { "deep": "#743B23", "head": "#24271A", "frame": "#D06A3F" },
  CUW: { "deep": "#464E5C", "head": "#CFC904", "frame": "#7E8DA6" },
  CIV: { "deep": "#3D5142", "head": "#D56405", "frame": "#6D9277" },
  ECU: { "deep": "#7F4C00", "head": "#2D3C6A", "frame": "#E48900" },
  NED: { "deep": "#7A3400", "head": "#86371B", "frame": "#DA5E00" },
  JPN: { "deep": "#853A14", "head": "#C34C2A", "frame": "#EE6825" },
  SWE: { "deep": "#252840", "head": "#D7A708", "frame": "#434873" },
  TUN: { "deep": "#76350F", "head": "#A3432E", "frame": "#D45F1B" },
  BEL: { "deep": "#72360E", "head": "#3C3C21", "frame": "#CD611A" },
  EGY: { "deep": "#71401F", "head": "#363B27", "frame": "#CA7338" },
  IRN: { "deep": "#42521C", "head": "#A33D2A", "frame": "#779433" },
  NZL: { "deep": "#3E4455", "head": "#B43124", "frame": "#707A99" },
  ESP: { "deep": "#732B07", "head": "#EFC406", "frame": "#CE4D0D" },
  CPV: { "deep": "#756C5A", "head": "#A4503A", "frame": "#D2C2A1" },
  KSA: { "deep": "#4D5913", "head": "#33371C", "frame": "#8A9F22" },
  URU: { "deep": "#444C5B", "head": "#556379", "frame": "#7A88A4" },
  FRA: { "deep": "#393D4E", "head": "#B84324", "frame": "#666D8C" },
  SEN: { "deep": "#7C3A00", "head": "#2F4F27", "frame": "#DF6800" },
  IRQ: { "deep": "#7A4C1E", "head": "#323625", "frame": "#DA8836" },
  NOR: { "deep": "#353943", "head": "#9B1F15", "frame": "#606679" },
  ARG: { "deep": "#16172C", "head": "#383D5D", "frame": "#292A4F" },
  ALG: { "deep": "#3E5133", "head": "#951615", "frame": "#70925C" },
  AUT: { "deep": "#652108", "head": "#98251B", "frame": "#B53C10" },
  JOR: { "deep": "#384D2F", "head": "#2C2515", "frame": "#648A54" },
  POR: { "deep": "#2C460B", "head": "#861E29", "frame": "#507E14" },
  COD: { "deep": "#3A434F", "head": "#9D2E27", "frame": "#69798E" },
  UZB: { "deep": "#3B4B47", "head": "#2F6313", "frame": "#6B8780" },
  COL: { "deep": "#754200", "head": "#222959", "frame": "#D17600" },
  ENG: { "deep": "#72301F", "head": "#832B15", "frame": "#CC5639" },
  CRO: { "deep": "#6D3B1A", "head": "#2A3451", "frame": "#C36B30" },
  GHA: { "deep": "#7A4D00", "head": "#325636", "frame": "#DB8B00" },
  PAN: { "deep": "#6F3622", "head": "#31396B", "frame": "#C7623E" },
};

export const ALBUM_TEAMS: Record<string, AlbumTeam> = {
  MEX: { pais: "MEXICO", grupo: "A", pagina: 10, roster: {
    "2": ["LUIS","MALAGÓN"],
    "3": ["JOHAN","VASQUEZ"],
    "4": ["JORGE","SÁNCHEZ"],
    "5": ["CESAR","MONTES"],
    "6": ["JESUS","GALLARDO"],
    "7": ["ISRAEL","REYES"],
    "8": ["DIEGO","LAINEZ"],
    "9": ["CARLOS","RODRIGUEZ"],
    "10": ["EDSON","ALVAREZ"],
    "11": ["ORBELIN","PINEDA"],
    "12": ["MARCEL","RUIZ"],
    "14": ["ÉRICK","SÁNCHEZ"],
    "15": ["HIRVING","LOZANO"],
    "16": ["SANTIAGO","GIMÉNEZ"],
    "17": ["RAÚL","JIMÉNEZ"],
    "18": ["ALEXIS","VEGA"],
    "19": ["ROBERTO","ALVARADO"],
    "20": ["CESAR","HUERTA"],
  } },
  RSA: { pais: "SOUTH AFRICA", grupo: "A", pagina: 12, roster: {
    "2": ["RONWEN","WILLIAMS"],
    "3": ["SIPHO","CHAINE"],
    "4": ["AUBREY","MODIBA"],
    "5": ["SAMUKELE","KABINI"],
    "6": ["MBEKEZELI","MBOKAZI"],
    "7": ["KHULUMANI","NDAMANE"],
    "8": ["SIYABONGA","NGEZANA"],
    "9": ["KHULISO","MUDAU"],
    "10": ["NKOSINATHI","SIBISI"],
    "11": ["TEBOHO","MOKOENA"],
    "12": ["THALENTE","MBATHA"],
    "14": ["BATHUSI","AUBAAS"],
    "15": ["YAYA","SITHOLE"],
    "16": ["SIPHO","MBULE"],
    "17": ["LYLE","FOSTER"],
    "18": ["IQRAAM","RAYNERS"],
    "19": ["MOHAU","NKOTA"],
    "20": ["OSWIN","APPOLLIS"],
  } },
  KOR: { pais: "SOUTH KOREA", grupo: "A", pagina: 14, roster: {
    "2": ["HYEON-WOO","JO"],
    "3": ["SEUNG-GYU","KIM"],
    "4": ["MIN-JAE","KIM"],
    "5": ["YU-MIN","CHO"],
    "6": ["YOUNG-WOO","SEOL"],
    "7": ["HAN-BEOM","LEE"],
    "8": ["TAE-SEOK","LEE"],
    "9": ["MYUNG-JAE","LEE"],
    "10": ["JAE-SUNG","LEE"],
    "11": ["IN-BEOM","HWANG"],
    "12": ["KANG-IN","LEE"],
    "14": ["SEUNG-HO","PAIK"],
    "15": ["JENS","CASTROP"],
    "16": ["DONGG-YEONG","LEE"],
    "17": ["GUE-SUNG","CHO"],
    "18": ["HEUNG-MIN","SON"],
    "19": ["HEE-CHAN","HWANG"],
    "20": ["HYEON-GYU","OH"],
  } },
  CZE: { pais: "CZECHIA", grupo: "A", pagina: 16, roster: {
    "2": ["MATEJ","KOVAR"],
    "3": ["JINDRICH","STANEK"],
    "4": ["LADISLAV","KREJCI"],
    "5": ["VLADIMIR","COUFAL"],
    "6": ["JAROSLAV","ZELENY"],
    "7": ["TOMAS","HOLES"],
    "8": ["DAVID","ZIMA"],
    "9": ["MICHAL","SADILEK"],
    "10": ["LUKAS","PROVOD"],
    "11": ["LUKAS","CERV"],
    "12": ["TOMAS","SOUCEK"],
    "14": ["PAVEL","SULC"],
    "15": ["MATEJ","VYDRA"],
    "16": ["VASIL","KUSEJ"],
    "17": ["TOMAS","CHORY"],
    "18": ["VACLAV","CERNY"],
    "19": ["ADAM","HLOZEK"],
    "20": ["PATRIK","SCHICK"],
  } },
  CAN: { pais: "CANADA", grupo: "B", pagina: 18, roster: {
    "2": ["DAYNE","ST.CLAIR"],
    "3": ["ALPHONSO","DAVIES"],
    "4": ["ALISTAIR","JOHNSTON"],
    "5": ["SAMUEL","ADEKUGBE"],
    "6": ["RICHE","LARVEA"],
    "7": ["DEREK","CORNELIUS"],
    "8": ["MOÏSE","BOMBITO"],
    "9": ["KAMAL","MILLER"],
    "10": ["STEPHEN","EUSTÁQUIO"],
    "11": ["ISMAËL","KONÉ"],
    "12": ["JONATHAN","OSORIO"],
    "14": ["JACOB","SHAFFELBURG"],
    "15": ["MATHIEU","CHOINIÈRE"],
    "16": ["NIKO","SIGUR"],
    "17": ["TAJON","BUCHANAN"],
    "18": ["LIAM","MILLAR"],
    "19": ["CYLE","LARIN"],
    "20": ["JONATHAN","DAVID"],
  } },
  BIH: { pais: "BOSNIA AND HERZEGOVINA", grupo: "B", pagina: 20, roster: {
    "2": ["NIKOLA","VASILJ"],
    "3": ["AMER","DEDIC"],
    "4": ["SEAD","KOLASINAC"],
    "5": ["TARIK","MUHAREMOVIC"],
    "6": ["NIHAD","MUJAKIC"],
    "7": ["NIKOLA","KATIC"],
    "8": ["AMIR","HADZIAHMETOVIC"],
    "9": ["BENJAMIN","TAHIROVIC"],
    "10": ["ARMIN","GIGOVIC"],
    "11": ["IVAN","SUNJIC"],
    "12": ["IVAN","BASIC"],
    "14": ["DZENIS","BURNIC"],
    "15": ["ESMIR","BAJRAKTAREVIC"],
    "16": ["AMAR","MEMIC"],
    "17": ["ERMEDIN","DEMIROVIC"],
    "18": ["EDIN","DZEKO"],
    "19": ["SAMED","BAZDAR"],
    "20": ["HARIS","TABAKOVIC"],
  } },
  QAT: { pais: "QATAR", grupo: "B", pagina: 22, roster: {
    "2": ["MESHAAL","BARSHAM"],
    "3": ["SULTAN","ALBRAKE"],
    "4": ["LUCAS","MENDES"],
    "5": ["HOMAM","AHMED"],
    "6": ["BOUALEM","KHOUKHI"],
    "7": ["PEDRO","MIGUEL"],
    "8": ["TAREK","SALMAN"],
    "9": ["MOHAMED","AL-MANNAI"],
    "10": ["KARIM","BOUDIAF"],
    "11": ["ASSIM","MADIBO"],
    "12": ["AHMED","FATEHI"],
    "14": ["MOHAMMED","WAAD"],
    "15": ["ABDULAZIZ","HATEM"],
    "16": ["HASSAN","AL-HAYDOS"],
    "17": ["EDMILSON","JUNIOR"],
    "18": ["AKRAM HASSAN","AFIF"],
    "19": ["AHMED","AL GANEHI"],
    "20": ["ALMOEZ","ALI"],
  } },
  SUI: { pais: "SWITZERLAND", grupo: "B", pagina: 24, roster: {
    "2": ["GREGOR","KOBEL"],
    "3": ["YVON","MVOGO"],
    "4": ["MANUEL","AKANJI"],
    "5": ["RICARDO","RODRIGUEZ"],
    "6": ["NICO","ELVEDI"],
    "7": ["AURÈLE","AMENDA"],
    "8": ["SILVAN","WIDMER"],
    "9": ["GRANIT","XHAKA"],
    "10": ["DENIS","ZAKARIA"],
    "11": ["REMO","FREULER"],
    "12": ["FABIAN","RIEDER"],
    "14": ["ARDON","JASHARI"],
    "15": ["JOHAN","MANZAMBI"],
    "16": ["MICHEL","AEBISCHER"],
    "17": ["BREEL","EMBOLO"],
    "18": ["RUBEN","VARGAS"],
    "19": ["DAN","NDOYE"],
    "20": ["ZEKI","AMDOUNI"],
  } },
  BRA: { pais: "BRAZIL", grupo: "C", pagina: 26, roster: {
    "2": ["","ALISSON"],
    "3": ["","BENTO"],
    "4": ["","MARQUINHOS"],
    "5": ["ÉDER","MILITÃO"],
    "6": ["GABRIEL","MAGALHÃES"],
    "7": ["","DANILO"],
    "8": ["","WESLEY"],
    "9": ["LUCAS","PAQUETÁ"],
    "10": ["","CASEMIRO"],
    "11": ["BRUNO","GUIMARÃES"],
    "12": ["LUIZ","HENRIQUE"],
    "14": ["VINICIUS","JÚNIOR"],
    "15": ["","RODRYGO"],
    "16": ["JOÃO","PEDRO"],
    "17": ["MATHEUS","CUNHA"],
    "18": ["GABRIEL","MARTINELLI"],
    "19": ["","RAPHINHA"],
    "20": ["","ESTÉVÃO"],
  } },
  MAR: { pais: "MOROCCO", grupo: "C", pagina: 28, roster: {
    "2": ["YASSINE","BOUNOU"],
    "3": ["MUNIR","EL KAJOUI"],
    "4": ["ACHRAF","HAKIMI"],
    "5": ["NOUSSAIR","MAZRAOUI"],
    "6": ["NAYEF","AGUERD"],
    "7": ["ROMAN","SAISS"],
    "8": ["JAWAD","EL YAMIO"],
    "9": ["ADAM","MASINA"],
    "10": ["SOFYAN","AMRABAT"],
    "11": ["AZZEDINE","OUNAHI"],
    "12": ["ELIESSE","BEN SEGHIR"],
    "14": ["BILAL","EL KHANNOUSS"],
    "15": ["ISMAEL","SAIBARI"],
    "16": ["YOUSSEF","EN-NESYRI"],
    "17": ["ABDE","EZZALZOULI"],
    "18": ["SOUFIANE","RAHIMI"],
    "19": ["BRAHIM","DIAZ"],
    "20": ["AYOUB","EL KAABI"],
  } },
  HAI: { pais: "HAITI", grupo: "C", pagina: 30, roster: {
    "2": ["JOHNY","PLACIDE"],
    "3": ["CARLENS","ARCUS"],
    "4": ["MARTIN","EXPÉRIENCE"],
    "5": ["JEAN-KEVIN","DUVERNE"],
    "6": ["RICARDO","ADÉ"],
    "7": ["DUKE","LACROIX"],
    "8": ["GARVEN","METUSALA"],
    "9": ["HANNES","DELCROIX"],
    "10": ["LEVERTON","PIERRE"],
    "11": ["DANLEY JEAN","JACQUES"],
    "12": ["JEAN-RICNER","BELLEGARDE"],
    "14": ["CHRISTOPHER","ATTYS"],
    "15": ["DERRICK ETIENNE","JR"],
    "16": ["JOSUE","CASIMIR"],
    "17": ["RUBEN","PROVIDENCE"],
    "18": ["DUCKENS","NAZON"],
    "19": ["LOUICIUS","DEEDSON"],
    "20": ["FRANTZDY","PIERROT"],
  } },
  SCO: { pais: "SCOTLAND", grupo: "C", pagina: 32, roster: {
    "2": ["ANGUS","GUNN"],
    "3": ["JACK","HENDRY"],
    "4": ["KIERAN","TIERNEY"],
    "5": ["AARON","HICKEY"],
    "6": ["ANDREW","ROBERTSON"],
    "7": ["SCOTT","MCKENNA"],
    "8": ["JOHN","SOUTTAR"],
    "9": ["ANTHONY","RALSTON"],
    "10": ["GRANT","HANLEY"],
    "11": ["SCOTT","MCTOMINAY"],
    "12": ["BILLY","GILMOUR"],
    "14": ["LEWIS","FERGUSON"],
    "15": ["RYAN","CHRISTIE"],
    "16": ["KENNY","MCLEAN"],
    "17": ["JOHN","MCGINN"],
    "18": ["LYNDON","DYKES"],
    "19": ["CHE","ADAMS"],
    "20": ["BEN","GANNON-DOAK"],
  } },
  USA: { pais: "USA", grupo: "D", pagina: 34, roster: {
    "2": ["MATH","FREESE"],
    "3": ["CHRIS","RICHARDS"],
    "4": ["TIM","REAM"],
    "5": ["MARK","MCKENZIE"],
    "6": ["ALEX","FREEMAN"],
    "7": ["ANTONEE","ROBINSON"],
    "8": ["TYLER","ADAMS"],
    "9": ["TANNER","TESSMANN"],
    "10": ["WESTON","MCKENNY"],
    "11": ["CHRISTIAN","ROLDAN"],
    "12": ["TIMOTHY","WEAH"],
    "14": ["DIEGO","LUNA"],
    "15": ["MALIK","TILLMAN"],
    "16": ["CHRISTIAN","PULISIC"],
    "17": ["BRENDEN","AARONSON"],
    "18": ["RICARDO","PEPI"],
    "19": ["HAJI","WRIGHT"],
    "20": ["FOLARIN","BALOGUN"],
  } },
  PAR: { pais: "PARAGUAY", grupo: "D", pagina: 36, roster: {
    "2": ["ROBERTO","FERNANDEZ"],
    "3": ["ORLANDO","GILL"],
    "4": ["GUSTAVO","GOMEZ"],
    "5": ["FABIÁN","BALBUENA"],
    "6": ["JUAN JOSÉ","CÁCERES"],
    "7": ["OMAR","ALDERETE"],
    "8": ["JUNIOR","ALONSO"],
    "9": ["MATHÍAS","VILLASANTI"],
    "10": ["DIEGO","GOMEZ"],
    "11": ["DAMIÁN","BOBADILLA"],
    "12": ["ANDRES","CUBAS"],
    "14": ["MATIAS GALARZA","FONDA"],
    "15": ["JULIO","ENCISO"],
    "16": ["ALEJANDRO ROMERO","GAMARRA"],
    "17": ["MIGUEL","ALMIRÓN"],
    "18": ["RAMON","SOSA"],
    "19": ["ANGEL","ROMERO"],
    "20": ["ANTONIO","SANABRIA"],
  } },
  AUS: { pais: "AUSTRALIA", grupo: "D", pagina: 38, roster: {
    "2": ["MATHEW","RYAN"],
    "3": ["JOE","GAUCI"],
    "4": ["HARRY","SOUTTAR"],
    "5": ["ALESSANDRO","CIRCATI"],
    "6": ["JORDAN","BOS"],
    "7": ["AZIZ","BEHICH"],
    "8": ["CAMERON","BURGESS"],
    "9": ["LEWIS","MILLER"],
    "10": ["MILOS","DEGENEK"],
    "11": ["JACKSON","IRVINE"],
    "12": ["RILEY","MCGREE"],
    "14": ["AIDEN","O'NEILL"],
    "15": ["CONNOR","METCALFE"],
    "16": ["PATRICK","YAZBEK"],
    "17": ["CRAIG","GOODWIN"],
    "18": ["KUSINI","VENGI"],
    "19": ["NESTORY","IRANKUNDA"],
    "20": ["MOHAMED","TOURÉ"],
  } },
  TUR: { pais: "TÜRKIYE", grupo: "D", pagina: 40, roster: {
    "2": ["UGURCAN","CAKIR"],
    "3": ["MERT","MULDUR"],
    "4": ["ZEKI","CELIK"],
    "5": ["ABDULKERIM","BARDAKCI"],
    "6": ["CAGLAR","SOYUNCU"],
    "7": ["MERIH","DEMIRAL"],
    "8": ["FERDI","KADIOGLU"],
    "9": ["KAAN","AYHAN"],
    "10": ["ISMAIL","YUKSEK"],
    "11": ["HAKAN","CALHANOGLU"],
    "12": ["ORKUN","KOKCU"],
    "14": ["ARDA","GULER"],
    "15": ["IRFAN CAN","KAHVECI"],
    "16": ["YUNUS","AKGUN"],
    "17": ["CAN","UZUN"],
    "18": ["BARIS ALPER","YILMAZ"],
    "19": ["KEREM","AKTURKOGLU"],
    "20": ["KENAN","YILDIZ"],
  } },
  GER: { pais: "GERMANY", grupo: "E", pagina: 42, roster: {
    "2": ["MARC-ANDRÉ","TER STEGEN"],
    "3": ["JONATHAN","TAH"],
    "4": ["DAVID","RAUM"],
    "5": ["NICO","SCHLOTTERBECK"],
    "6": ["ANTONIO","RÜDIGER"],
    "7": ["WALDEMAR","ANTON"],
    "8": ["RIDLE","BAKU"],
    "9": ["MAXIMILIAN","MITTELSTADT"],
    "10": ["JOSHUA","KIMMICH"],
    "11": ["FLORIAN","WIRTZ"],
    "12": ["FELIX","NMECHA"],
    "14": ["LEON","GORETZKA"],
    "15": ["JAMAL","MUSIALA"],
    "16": ["SERGE","GNABRY"],
    "17": ["KAI","HAVERTZ"],
    "18": ["LEROY","SANE"],
    "19": ["KARIM","ADEYEMI"],
    "20": ["NICK","WOLTEMADE"],
  } },
  CUW: { pais: "CURAÇAO", grupo: "E", pagina: 44, roster: {
    "2": ["ELOY","ROOM"],
    "3": ["ARMANDO","OBISPO"],
    "4": ["SHEREL","FLORANUS"],
    "5": ["JURIEN","GAARI"],
    "6": ["JOSHUA","BRENET"],
    "7": ["ROSHON","VAN EIJMA"],
    "8": ["SHURANDY","SAMBO"],
    "9": ["LIVANO","COMENENCIA"],
    "10": ["GODFRIED","ROEMERATOE"],
    "11": ["JUNINHO","BACUNA"],
    "12": ["LEANDRO","BACUNA"],
    "14": ["TAHITH","CHONG"],
    "15": ["KENJI","GORRE"],
    "16": ["JEARL","MARGARITHA"],
    "17": ["JURGEN","LOCADIA"],
    "18": ["JEREMY","ANTONISSE"],
    "19": ["GERVANE","KASTANEER"],
    "20": ["SONTJE","HANSEN"],
  } },
  CIV: { pais: "IVORY COAST", grupo: "E", pagina: 46, roster: {
    "2": ["YAHIA","FOFANA"],
    "3": ["GHISLAIN","KONAN"],
    "4": ["WILFRIED","SINGO"],
    "5": ["ODILON","KOSSOUNOU"],
    "6": ["EVAN","NDICKA"],
    "7": ["WILLY","BOLY"],
    "8": ["EMMANUEL","AGBADOU"],
    "9": ["OUSMANE","DIOMANDE"],
    "10": ["FRANCK","KESSIE"],
    "11": ["SEKO","FOFANA"],
    "12": ["IBRAHIM","SANGARE"],
    "14": ["JEAN-PHILIPPE","GBAMIN"],
    "15": ["AMAD","DIALLO"],
    "16": ["SÉBASTIEN","HALLER"],
    "17": ["SIMON","ADINGRA"],
    "18": ["YAN","DIOMANDE"],
    "19": ["EVANN","GUESSAND"],
    "20": ["OUMAR","DIAKITE"],
  } },
  ECU: { pais: "ECUADOR", grupo: "E", pagina: 48, roster: {
    "2": ["HERNÁN","GALÍNDEZ"],
    "3": ["GONZALO","VALLE"],
    "4": ["PIERO","HINCAPIÉ"],
    "5": ["PERVIS","ESTUPIÑÁN"],
    "6": ["WILLIAN","PACHO"],
    "7": ["ÁNGELO","PRECIADO"],
    "8": ["JOEL","ORDÓÑEZ"],
    "9": ["MOISES","CAICEDO"],
    "10": ["ALAN","FRANCO"],
    "11": ["KENDRY","PAEZ"],
    "12": ["PEDRO","VITE"],
    "14": ["JOHN","VEBOAH"],
    "15": ["LEONARDO","CAMPANA"],
    "16": ["GONZALO","PLATA"],
    "17": ["NILSON","ANGULO"],
    "18": ["ALAN","MINDA"],
    "19": ["KEVIN","RODRIGUEZ"],
    "20": ["ENNER","VALENCIA"],
  } },
  NED: { pais: "NETHERLANDS", grupo: "F", pagina: 50, roster: {
    "2": ["BART","VERBRUGGEN"],
    "3": ["VIRGIL","VAN DIJK"],
    "4": ["MICKY","VAN DE VEN"],
    "5": ["JURRIEN","TIMBER"],
    "6": ["DENZEL","DUMFRIES"],
    "7": ["NATHAN","AKÉ"],
    "8": ["JEREMIE","FRIMPONG"],
    "9": ["JAN PAUL","VAN HECKE"],
    "10": ["TIJJANI","REIJNDERS"],
    "11": ["RYAN","GRAVENBERCH"],
    "12": ["TEUN","KOOPMEINERS"],
    "14": ["FRENKIE","DE JONG"],
    "15": ["XAVI","SIMONS"],
    "16": ["JUSTIN","KLUIVERT"],
    "17": ["MEMPHIS","DEPAY"],
    "18": ["DONYELL","MALEN"],
    "19": ["WOUT","WEGHORST"],
    "20": ["CODY","GAKPO"],
  } },
  JPN: { pais: "JAPAN", grupo: "F", pagina: 52, roster: {
    "2": ["ZION","SUZUKI"],
    "3": ["HENRY HEROKI","MOCHIZUKI"],
    "4": ["AYUMU","SEKO"],
    "5": ["JUNNOSUKE","SUZUKI"],
    "6": ["SHOGO","TANIGUCHI"],
    "7": ["TSUYOSHI","WATANABE"],
    "8": ["KAISHU","SANO"],
    "9": ["YUKI","SOMA"],
    "10": ["AO","TANAKA"],
    "11": ["DAICHI","KAMADA"],
    "12": ["TAKEFUSA","KUBO"],
    "14": ["RITSU","DOAN"],
    "15": ["KEITO","NAKAMURA"],
    "16": ["TAKUMI","MINAMINO"],
    "17": ["SHUTO","MACHINO"],
    "18": ["JUNYA","ITO"],
    "19": ["KOKI","OGAWA"],
    "20": ["AYASE","UEDA"],
  } },
  SWE: { pais: "SWEDEN", grupo: "F", pagina: 54, roster: {
    "2": ["VICTOR","JOHANSSON"],
    "3": ["ISAK","HIEN"],
    "4": ["GABRIEL","GUDMUNDSSON"],
    "5": ["EMIL","HOLM"],
    "6": ["VICTOR NILSSON","LINDELÖF"],
    "7": ["GUSTAF","LAGERBIELKE"],
    "8": ["LUCAS","BERGVALL"],
    "9": ["HUGO","LARSSON"],
    "10": ["JESPER","KARLSTRÖM"],
    "11": ["YASIN","AYARI"],
    "12": ["MATTIAS","SVANBERG"],
    "14": ["DANIEL","SVENSSON"],
    "15": ["KEN","SEMA"],
    "16": ["ROONY","BARDGHJI"],
    "17": ["DEJAN","KULUSEVSKI"],
    "18": ["ANTHONY","ELANGA"],
    "19": ["ALEXANDER","ISAK"],
    "20": ["VIKTOR","GYÖKERES"],
  } },
  TUN: { pais: "TUNISIA", grupo: "F", pagina: 56, roster: {
    "2": ["BECHIR","BEN SAID"],
    "3": ["AYMEN","DAHMEN"],
    "4": ["YAN","VALERY"],
    "5": ["MONTASSAR","TALBI"],
    "6": ["YASSINE","MERIAH"],
    "7": ["ALI","ABDI"],
    "8": ["DYLAN","BRONN"],
    "9": ["ELLYES","SKHIRI"],
    "10": ["AISSA","LAIDOUNI"],
    "11": ["FERJANI","SASSI"],
    "12": ["MOHAMED ALI","BEN ROMDHANE"],
    "14": ["HANNIBAL","MEJBRI"],
    "15": ["ELIAS","ACHOURI"],
    "16": ["ELIAS","SAAD"],
    "17": ["HAZEM","MASTOURI"],
    "18": ["ISMAEL","GHARBI"],
    "19": ["SAYFALLAH","LTAIEF"],
    "20": ["NAIM","SLITI"],
  } },
  BEL: { pais: "BELGIUM", grupo: "G", pagina: 64, roster: {
    "2": ["THIBAUT","COURTOIS"],
    "3": ["ARTHUR","THEATE"],
    "4": ["TIMOTHY","CASTAGNE"],
    "5": ["ZENO","DEBAST"],
    "6": ["BRANDON","MECHELE"],
    "7": ["MAXIM","DE CUYPER"],
    "8": ["THOMAS","MEUNIER"],
    "9": ["YOURI","TIELEMANS"],
    "10": ["AMADOU","ONANA"],
    "11": ["NICOLAS","RASKIN"],
    "12": ["ALEXIS","SAELEMAEKERS"],
    "14": ["HANS","VANAKEN"],
    "15": ["KEVIN","DE BRUYNE"],
    "16": ["JÉRÉMY","DOKU"],
    "17": ["CHARLES","DE KETELAERE"],
    "18": ["LEANDRO","TROSSARD"],
    "19": ["LOÏS","OPENDA"],
    "20": ["ROMELU","LUKAKU"],
  } },
  EGY: { pais: "EGYPT", grupo: "G", pagina: 66, roster: {
    "2": ["MOHAMED","EL SHENAWY"],
    "3": ["MOHAMED","HANY"],
    "4": ["MOHAMED","HAMDY"],
    "5": ["YASSER","IBRAHIM"],
    "6": ["KHALED","SOBHI"],
    "7": ["RAMY","RABIA"],
    "8": ["HOSSAM","ABDELMAGUID"],
    "9": ["AHMED","FATOUH"],
    "10": ["MARWAN","ATTIA"],
    "11": ["","ZIZO"],
    "12": ["HAMDY","FATHY"],
    "14": ["MOHAMED","LASHEEN"],
    "15": ["EMAM","ASHOUR"],
    "16": ["OSAMA","FAISAL"],
    "17": ["MOHAMED","SALAH"],
    "18": ["MOSTAFA","MOHAMED"],
    "19": ["","TREZEGUET"],
    "20": ["OMAR","MARMOUSH"],
  } },
  IRN: { pais: "IRAN", grupo: "G", pagina: 68, roster: {
    "2": ["ALIREZA","BEIRANVAND"],
    "3": ["MORTEZA","POURALIGANJI"],
    "4": ["EHSAN","HAJSAFI"],
    "5": ["MILAD","MOHAMMADI"],
    "6": ["SHOJAE","KHALILZADEH"],
    "7": ["RAMIN","REZAEIAN"],
    "8": ["HOSSEIN","KANAANI"],
    "9": ["SADEGH","MOHARRAMI"],
    "10": ["SALEH","HARDANI"],
    "11": ["SAEED","EZATOLAHI"],
    "12": ["SAMAN","GHODDOS"],
    "14": ["OMID","NOORAFKAN"],
    "15": ["ROOZBEH","CHESHMI"],
    "16": ["MOHAMMAD","MOHEBI"],
    "17": ["SARDAR","AZMOUN"],
    "18": ["MEHDI","TAREMI"],
    "19": ["ALIREZA","JAHANBAKHSH"],
    "20": ["ALI","GHOLIZADEH"],
  } },
  NZL: { pais: "NEW ZEALAND", grupo: "G", pagina: 70, roster: {
    "2": ["MAX CROCOMBE","PAYNE"],
    "3": ["ALEX","PAULSEN"],
    "4": ["MICHAEL","BOXALL"],
    "5": ["LIBERATO","CACACE"],
    "6": ["TIM","PAYNE"],
    "7": ["TYLER","BINDON"],
    "8": ["FRANCIS","DE VRIES"],
    "9": ["FINN","SURMAN"],
    "10": ["JOE","BELL"],
    "11": ["SARPREET","SINGH"],
    "12": ["RYAN","THOMAS"],
    "14": ["MATTHEW","GARBETT"],
    "15": ["MARKO","STAMENIĆ"],
    "16": ["BEN","OLD"],
    "17": ["CHRIS","WOOD"],
    "18": ["ELIJAH","JUST"],
    "19": ["CALLUM","MCCOWATT"],
    "20": ["KOSTA","BARBAROUSES"],
  } },
  ESP: { pais: "SPAIN", grupo: "H", pagina: 72, roster: {
    "2": ["UNAI","SIMON"],
    "3": ["ROBIN","LE NORMAND"],
    "4": ["AYMERIC","LAPORTE"],
    "5": ["DEAN","HUIJSEN"],
    "6": ["PEDRO","PORRO"],
    "7": ["DANI","CARVAJAL"],
    "8": ["MARC","CUCURELLA"],
    "9": ["MARTÍN","ZUBIMENDI"],
    "10": ["","RODRI"],
    "11": ["","PEDRI"],
    "12": ["FABIAN","RUIZ"],
    "14": ["MIKEL","MERINO"],
    "15": ["LAMINE","YAMAL"],
    "16": ["DANI","OLMO"],
    "17": ["NICO","WILLIAMS"],
    "18": ["FERRAN","TORRES"],
    "19": ["ÁLVARO","MORATA"],
    "20": ["MIKEL","OYARZABAL"],
  } },
  CPV: { pais: "CAPE VERDE", grupo: "H", pagina: 74, roster: {
    "2": ["","VOZINHA"],
    "3": ["LOGAN","COSTA"],
    "4": ["","PICO"],
    "5": ["","DINEY"],
    "6": ["STEVEN","MOREIRA"],
    "7": ["WAGNER","PINA"],
    "8": ["JOAO","PAULO"],
    "9": ["YANNICK","SEMEDO"],
    "10": ["KEVIN","PINA"],
    "11": ["PATRICK","ANDRADE"],
    "12": ["JAMIRO","MONTEIRO"],
    "14": ["DEROY","DUARTE"],
    "15": ["GARRY","RODRIGUES"],
    "16": ["JOVANE","CABRAL"],
    "17": ["RYAN","MENDES"],
    "18": ["DAILON","LIVRAMENTO"],
    "19": ["WILLY","SEMEDO"],
    "20": ["","BEBE"],
  } },
  KSA: { pais: "SAUDI ARABIA", grupo: "H", pagina: 76, roster: {
    "2": ["NAWAF","ALAQIDI"],
    "3": ["ABDULRAHMAN","AL-SANBI"],
    "4": ["SAUD","ABDULHAMID"],
    "5": ["NAWAF","BOUWASHL"],
    "6": ["JIHAD","THAKRI"],
    "7": ["MOTEB","AL-HARBI"],
    "8": ["HASSAN","ALTAMBAKTI"],
    "9": ["MUSAB","ALJUWAYR"],
    "10": ["ZIYAD","ALJOHANI"],
    "11": ["ABDULLAH","ALKHAIBARI"],
    "12": ["NASSER","ALDAWSARI"],
    "14": ["SALEH","ABU ALSHAMAT"],
    "15": ["MARWAN","ALSAHAFI"],
    "16": ["SALEM","ALDAWSARI"],
    "17": ["ABDULRAHMAN","AL-ABOUD"],
    "18": ["FERAS","AKBRIKAN"],
    "19": ["SALEH","ALSHEHRI"],
    "20": ["ABDULLAH","AL-HAMDAN"],
  } },
  URU: { pais: "URUGUAY", grupo: "H", pagina: 78, roster: {
    "2": ["SERGIO","ROCHET"],
    "3": ["SANTIAGO","MELE"],
    "4": ["RONALD","ARAUJO"],
    "5": ["JOSÉ MARÍA","GIMÉNEZ"],
    "6": ["SEBASTIAN","CACERES"],
    "7": ["MATHIAS","OLIVERA"],
    "8": ["GUILLERMO","VARELA"],
    "9": ["NAHITAN","NANDEZ"],
    "10": ["FEDERICO","VALVERDE"],
    "11": ["GIORGIAN","DE ARRASCAETA"],
    "12": ["RODRIGO","BENTANCUR"],
    "14": ["MANUEL","UGARTE"],
    "15": ["NICOLÁS","DE LA CRUZ"],
    "16": ["MAXI","ARAUJO"],
    "17": ["DARWIN","NÚÑEZ"],
    "18": ["FEDERICO","VIÑAS"],
    "19": ["RODRIGO","AGUIRRE"],
    "20": ["FACUNDO","PELLISTRI"],
  } },
  FRA: { pais: "FRANCE", grupo: "I", pagina: 80, roster: {
    "2": ["MIKE","MAIGNAN"],
    "3": ["THEO","HERNANDEZ"],
    "4": ["WILLIAM","SALIBA"],
    "5": ["JULES","KOUNDE"],
    "6": ["IBRAHIMA","KONATE"],
    "7": ["DAYOT","UPAMECANO"],
    "8": ["LUCAS","DIGNE"],
    "9": ["AURÉLIEN","TCHOUAMÉNI"],
    "10": ["EDUARDO","CAMAVINGA"],
    "11": ["MANU","KONE"],
    "12": ["ADRIEN","RABIOT"],
    "14": ["MICHAEL","OLISE"],
    "15": ["OUSMANE","DEMBELE"],
    "16": ["BRADLEY","BARCOLA"],
    "17": ["DÉSIRÉ","DOUÉ"],
    "18": ["KINGSLEY","COMAN"],
    "19": ["HUGO","EKITIKE"],
    "20": ["KYLIAN","MBAPPE"],
  } },
  SEN: { pais: "SENEGAL", grupo: "I", pagina: 82, roster: {
    "2": ["EDOUARD","MENDY"],
    "3": ["YEHVANN","DIOUF"],
    "4": ["MOUSSA","NIAKHATÉ"],
    "5": ["ABDOULAYE","SECK"],
    "6": ["ISMAIL","JAKOBS"],
    "7": ["EL HADJI MALICK","DIOUF"],
    "8": ["KALIDOU","KOULIBALY"],
    "9": ["IDRISSA GANA","GUEYE"],
    "10": ["PAPE MATAR","SARR"],
    "11": ["PAPE","GUEYE"],
    "12": ["HABIB","DIARRA"],
    "14": ["LAMINE","CAMARA"],
    "15": ["SADIO","MANE"],
    "16": ["ISMAÏLA","SARR"],
    "17": ["BOULAYE","DIA"],
    "18": ["ILIMAN","NDIAYE"],
    "19": ["NICOLAS","JACKSON"],
    "20": ["KREPIN","DIATTA"],
  } },
  IRQ: { pais: "IRAQ", grupo: "I", pagina: 84, roster: {
    "2": ["JALAL","HASSAN"],
    "3": ["REBIN","SULAKA"],
    "4": ["HUSSEIN","ALI"],
    "5": ["AKAM","HASHEM"],
    "6": ["MERCHAS","DOSKI"],
    "7": ["ZAID","TAHSEEN"],
    "8": ["MANAF","YOUNIS"],
    "9": ["ZIDANE","IQBAL"],
    "10": ["AMIR","AL-AMMARI"],
    "11": ["IBRAHIM","BAVESH"],
    "12": ["ALI","JASIM"],
    "14": ["YOUSSEF","AMYN"],
    "15": ["AIMAR","SHER"],
    "16": ["MARKO","FARJI"],
    "17": ["OSAMA","RASHID"],
    "18": ["ALI","AL-HAMADI"],
    "19": ["AYMEN","HUSSEIN"],
    "20": ["MOHANAD","ALI"],
  } },
  NOR: { pais: "NORWAY", grupo: "I", pagina: 86, roster: {
    "2": ["ORJAN","NYLAND"],
    "3": ["JULIAN","RYERSON"],
    "4": ["LEO","OSTIGÅRD"],
    "5": ["KRISTOFFER VASSBAKK","AJER"],
    "6": ["MARCUS HOLMGREN","PEDERSEN"],
    "7": ["DAVID MØLLER","WOLFE"],
    "8": ["TORBJØRN","HEGGEM"],
    "9": ["MORTEN","THORSBY"],
    "10": ["MARTIN","ØDEGAARD"],
    "11": ["SANDER","BERGE"],
    "12": ["ANDREAS","SCHJELDERUP"],
    "14": ["PATRICK","BERG"],
    "15": ["ERLING","HAALAND"],
    "16": ["ALEXANDER","SØRLOTH"],
    "17": ["ARON","DØNNUM"],
    "18": ["JORGEN STRAND","LARSEN"],
    "19": ["ANTONIO","NUSA"],
    "20": ["OSCAR","BOBB"],
  } },
  ARG: { pais: "ARGENTINA", grupo: "J", pagina: 88, roster: {
    "2": ["EMILIANO","MARTINEZ"],
    "3": ["NAHUEL","MOLINA"],
    "4": ["CRISTIAN","ROMERO"],
    "5": ["NICOLAS","OTAMENDI"],
    "6": ["NICOLAS","TAGLIAFICO"],
    "7": ["LEONARDO","BALERDI"],
    "8": ["ENZO","FERNANDEZ"],
    "9": ["ALEXIS","MAC ALLISTER"],
    "10": ["RODRIGO","DE PAUL"],
    "11": ["EXEQUIEL","PALACIOS"],
    "12": ["LEANDRO","PAREDES"],
    "14": ["NICO","PAZ"],
    "15": ["FRANCO","MASTANTUONO"],
    "16": ["NICO","GONZALEZ"],
    "17": ["LIONEL","MESSI"],
    "18": ["LAUTARO","MARTINEZ"],
    "19": ["JULIAN","ALVAREZ"],
    "20": ["GIULIANO","SIMEONE"],
  } },
  ALG: { pais: "ALGERIA", grupo: "J", pagina: 90, roster: {
    "2": ["ALEXIS","GUENDOUZ"],
    "3": ["RAMY","BENSEBAINI"],
    "4": ["YOUCEF","ATAL"],
    "5": ["RAYAN","AÏT-NOURI"],
    "6": ["MOHAMED AMINE","TOUGAI"],
    "7": ["AÏSSA","MANDI"],
    "8": ["ISMAEL","BENNACER"],
    "9": ["HOUSSEM","AQUAR"],
    "10": ["HICHAM","BOUDAOUI"],
    "11": ["RAMIZ","ZERROUKI"],
    "12": ["NABIL","BENTALAB"],
    "14": ["FARÉS","CHAIBI"],
    "15": ["RIYAD","MAHREZ"],
    "16": ["SAID","BENRAHMA"],
    "17": ["ANIS HADJ","MOUSSA"],
    "18": ["AMINE","GOUIRI"],
    "19": ["BAGHDAD","BOUNEDJAH"],
    "20": ["MOHAMMED","AMOURA"],
  } },
  AUT: { pais: "AUSTRIA", grupo: "J", pagina: 92, roster: {
    "2": ["ALEXANDER","SCHLAGER"],
    "3": ["PATRICK","PENTZ"],
    "4": ["DAVID","ALABA"],
    "5": ["KEVIN","DANSO"],
    "6": ["PHILIPP","LIENHART"],
    "7": ["STEFAN","POSCH"],
    "8": ["PHILLIPP","MWENE"],
    "9": ["ALEXANDER","PRASS"],
    "10": ["XAVER","SCHLAGER"],
    "11": ["MARCEL","SABITZER"],
    "12": ["KONRAD","LAIMER"],
    "14": ["FLORIAN","GRILLITSCH"],
    "15": ["NICOLAS","SEIWALD"],
    "16": ["ROMANO","SCHMID"],
    "17": ["PATRICK","WIMMER"],
    "18": ["CHRISTOPH","BAUMGARTNER"],
    "19": ["MICHAEL","GREGORITSCH"],
    "20": ["MARKO","ARNAUTOVIĆ"],
  } },
  JOR: { pais: "JORDAN", grupo: "J", pagina: 94, roster: {
    "2": ["YAZEED","ABULAILA"],
    "3": ["IHSAN","HADDAD"],
    "4": ["MOHAMMAD","ABU HASHISH"],
    "5": ["YAZAN","AL-ARAB"],
    "6": ["ABDALLAH","NASIB"],
    "7": ["SALEEM","OBAID"],
    "8": ["MOHAMMAD","ABUALNADI"],
    "9": ["IBRAHIM","SAADEH"],
    "10": ["NIZAR","AL-RASHDAN"],
    "11": ["NOOR","AL-RAWABDEH"],
    "12": ["MOHANNAD","ABU TAHA"],
    "14": ["AMER","JAMOUS"],
    "15": ["MUSA","AL-TAAMARI"],
    "16": ["YAZAN","AL-NAIMAT"],
    "17": ["MAHMOUD","AL-MARDI"],
    "18": ["ALI","OLWAN"],
    "19": ["MOHAMMAD","ABU ZRAYQ"],
    "20": ["IBRAHIM","SABRA"],
  } },
  POR: { pais: "PORTUGAL", grupo: "K", pagina: 96, roster: {
    "2": ["DIOGO","COSTA"],
    "3": ["JOSE","SA"],
    "4": ["RUBEN","DIAS"],
    "5": ["JOÃO","CANCELO"],
    "6": ["DIOGO","DALOT"],
    "7": ["NUNO","MENDES"],
    "8": ["GONÇALO","INÁCIO"],
    "9": ["BERNARDO","SILVA"],
    "10": ["BRUNO","FERNANDES"],
    "11": ["RUBEN","NEVES"],
    "12": ["","VITINHA"],
    "14": ["JOÃO","NEVES"],
    "15": ["CRISTIANO","RONALDO"],
    "16": ["FRANCISCO","TRINCAO"],
    "17": ["JOÃO","FELIX"],
    "18": ["GONÇALO","RAMOS"],
    "19": ["PEDRO","NETO"],
    "20": ["RAFAEL","LEÃO"],
  } },
  COD: { pais: "CONGO DR", grupo: "K", pagina: 98, roster: {
    "2": ["LIONEL","MPASI"],
    "3": ["AARON","WAN-BISSAKA"],
    "4": ["AXEL","TUANZEBE"],
    "5": ["ARTHUR","MASUAKU"],
    "6": ["CHANCEL","MBEMBA"],
    "7": ["JORIS","KAYEMBE"],
    "8": ["CHARLES","PICKEL"],
    "9": ["NGAL'AYEL","MUKAU"],
    "10": ["EDO","KAYEMBE"],
    "11": ["SAMUEL","MOUTOUSSAMY"],
    "12": ["NOAH","SADIKI"],
    "14": ["THÉO","BONGONDA"],
    "15": ["MESCHAK","ELIA"],
    "16": ["YOANE","WISSA"],
    "17": ["BRIAN","CIPENGA"],
    "18": ["FISTON","MAYELE"],
    "19": ["CÉDRIC","BAKAMBU"],
    "20": ["NATHANAËL","MBUKU"],
  } },
  UZB: { pais: "UZBEKISTAN", grupo: "K", pagina: 100, roster: {
    "2": ["UTKIR","YUSUPOV"],
    "3": ["FARRUKH","SAVFIEV"],
    "4": ["SHERZOD","NASRULLAEV"],
    "5": ["UMAR","ESHMURODOV"],
    "6": ["HUSNIDDIN","ALIQULOV"],
    "7": ["RUSTAMJON","ASHURMATOV"],
    "8": ["KHOJIAKBAR","ALIJONOV"],
    "9": ["ABDUKODIR","KHUSANOV"],
    "10": ["ODILJON","HAMROBEKOV"],
    "11": ["OTABEK","SHUKUROV"],
    "12": ["JAMSHID","ISKANDEROV"],
    "14": ["AZIZBEK","TURGUNBOEV"],
    "15": ["KHOJIMAT","ERKINOV"],
    "16": ["ELDOR","SHOMURODOV"],
    "17": ["OSTON","URUNOV"],
    "18": ["JALOLIDDIN","MASHARIPOV"],
    "19": ["IGOR","SERGEEV"],
    "20": ["ABBOSBEK","FAYZULLAEV"],
  } },
  COL: { pais: "COLOMBIA", grupo: "K", pagina: 102, roster: {
    "2": ["CAMILO","VARGAS"],
    "3": ["DAVID","OSPINA"],
    "4": ["DÁVINSON","SÁNCHEZ"],
    "5": ["YERRY","MINA"],
    "6": ["DANIEL","MUNOZ"],
    "7": ["JOHAN","MOJICA"],
    "8": ["JHON","LUCUMÍ"],
    "9": ["SANTIAGO","ARIAS"],
    "10": ["JEFFERSON","LERMA"],
    "11": ["KEVIN","CASTAÑO"],
    "12": ["RICHARD","RIOS"],
    "14": ["JAMES","RODRIGUEZ"],
    "15": ["JUAN FERNANDO","QUINTERO"],
    "16": ["JORGE","CARRASCAL"],
    "17": ["JON","ARIAS"],
    "18": ["JHON","CORDOVA"],
    "19": ["LUIS","SUAREZ"],
    "20": ["LUIS","DIAZ"],
  } },
  ENG: { pais: "ENGLAND", grupo: "L", pagina: 104, roster: {
    "2": ["JORDAN","PICKFORD"],
    "3": ["JOHN","STONES"],
    "4": ["MARC","GUÉHI"],
    "5": ["EZRI","KONSA"],
    "6": ["TRENT","ALEXANDER-ARNOLD"],
    "7": ["REECE","JAMES"],
    "8": ["DAN","BURN"],
    "9": ["JORDAN","HENDERSON"],
    "10": ["DECLAN","RICE"],
    "11": ["JUDE","BELLINGHAM"],
    "12": ["COLE","PALMER"],
    "14": ["MORGAN","ROGERS"],
    "15": ["ANTHONY","GORDON"],
    "16": ["PHIL","FODEN"],
    "17": ["BUKAYO","SAKA"],
    "18": ["HARRY","KANE"],
    "19": ["MARCUS","RASHFORD"],
    "20": ["OLLIE","WATKINS"],
  } },
  CRO: { pais: "CROATIA", grupo: "L", pagina: 106, roster: {
    "2": ["DOMINIK","LIVAKOVIĆ"],
    "3": ["DUJE","CALETA-CAR"],
    "4": ["JOSKO","GVARDIOL"],
    "5": ["JOSIP","STANIŠIĆ"],
    "6": ["LUKA","VUŠKOVIĆ"],
    "7": ["JOSIP","SUTALO"],
    "8": ["KRISTIJAN","JAKIC"],
    "9": ["LUKA","MODRIĆ"],
    "10": ["MATEO","KOVACIC"],
    "11": ["MARTIN","BATURINA"],
    "12": ["LOVRO","MAJER"],
    "14": ["MARIO","PASALIC"],
    "15": ["PETAR","SUCIC"],
    "16": ["IVAN","PERIŠIĆ"],
    "17": ["MARCO","PASALIC"],
    "18": ["ANTE","BUDIMIR"],
    "19": ["ANDREJ","KRAMARIĆ"],
    "20": ["FRANJO","IVANOVIC"],
  } },
  GHA: { pais: "GHANA", grupo: "L", pagina: 108, roster: {
    "2": ["LAWRENCE ATI","ZIGI"],
    "3": ["TARIQ","LAMPTEY"],
    "4": ["MOHAMMED","SALISU"],
    "5": ["ALIDU","SEIDU"],
    "6": ["ALEXANDER","DJIKU"],
    "7": ["GIDEON","MENSAH"],
    "8": ["CALEB","YIRENKYI"],
    "9": ["ABDUL ISSAHAKU","FATAWU"],
    "10": ["THOMAS","PARTEY"],
    "11": ["SALIS ABDUL","SAMED"],
    "12": ["KAMALDEEN","SULEMANA"],
    "14": ["MOHAMMED","KUDUS"],
    "15": ["INAKI","WILLIAMS"],
    "16": ["JORDAN","AYEW"],
    "17": ["ANDREW","AYEW"],
    "18": ["JOSEPH","PAINTSIL"],
    "19": ["OSMAN","BUKARI"],
    "20": ["ANTOINE","SEMENYO"],
  } },
  PAN: { pais: "PANAMA", grupo: "L", pagina: 110, roster: {
    "2": ["ORLANDO","MOSQUERA"],
    "3": ["LUIS","MEJIA"],
    "4": ["FIDEL","ESCOBAR"],
    "5": ["ANDRES","ANDRADE"],
    "6": ["MICHAEL AMIR","MURILLO"],
    "7": ["ERIC","DAVIS"],
    "8": ["JOSE","CORDOBA"],
    "9": ["CESAR","BLACKMAN"],
    "10": ["CRISTIAN","MARTINEZ"],
    "11": ["ANÍBAL","GODOY"],
    "12": ["ADALBERTO","CARRASQUILLA"],
    "14": ["ÉDGAR","BÁRCENAS"],
    "15": ["CARLOS","HARVEY"],
    "16": ["ISMAEL","DÍAZ"],
    "17": ["JOSE","FAJARDO"],
    "18": ["CECILIO","WATERMAN"],
    "19": ["JOSE LUIZ","RODRIGUEZ"],
    "20": ["ALBERTO","QUINTERO"],
  } },
};

// Extras verificados SOLO para RSA y NED (no inventar para el resto).
export const VERIF: Record<string, VerifExtra> = {
  "NED": {
    "fed": "Koninklijke Nederlandse Voetbalbond",
    "mlang": "Nederland | Niederlande | Pays-Bas | Paesi Bassi | Países Bajos | Países Baixos | Hollanda | Holandia | Нидерланды"
  },
  "RSA": {
    "fed": "South African Football Association",
    "mlang": "South Africa | Südafrika | Afrique du Sud | Sudafrica | Zuid-Afrika | Sudáfrica | África do Sul | Güney Afrika Cumhuriyeti | Południowa Afryka | Южно-Африканская Республика",
    "quali": [
      "South Africa – Zimbabwe",
      "Rwanda – South Africa",
      "South Africa – Lesotho"
    ],
    "partidos": [
      {
        "a": "Mexico",
        "b": "South Africa",
        "hl": "b",
        "fecha": "Thursday, 11 June – Mexico City Stadium"
      },
      {
        "a": "Czechia",
        "b": "South Africa",
        "hl": "b",
        "fecha": "Thursday, 18 June – Atlanta Stadium"
      },
      {
        "a": "South Africa",
        "b": "Korea Republic",
        "hl": "a",
        "fecha": "Wednesday, 24 June – Monterrey Stadium"
      }
    ]
  }
};
